export const extendExternals = () => {
  return {
    'm-page': () => [require('../../../mobile/src/m-page')],
    'm-badge': () => [require('../../../mobile/src/m-badge')],
    'm-button': () => [require('../../../mobile/src/m-button')],
    'm-fab-backdrop': () => [require('../../../mobile/src/m-fab-backdrop')],
    'm-fab-button': () => [require('../../../mobile/src/m-fab-button')],
    'm-fab-buttons': () => [require('../../../mobile/src/m-fab-buttons')],
    'm-fab': () => [require('../../../mobile/src/m-fab')],
    'm-input': () => [require('../../../mobile/src/m-input')],
    'm-link': () => [require('../../../mobile/src/m-link')],
    'm-list-group': () => [require('../../../mobile/src/m-list-group')],
    'm-list-item': () => [require('../../../mobile/src/m-list-item')],
    'm-list-input': () => [require('../../../mobile/src/m-list-input')],
    'm-list': () => [require('../../../mobile/src/m-list')],
    'm-nav-left': () => [require('../../../mobile/src/m-nav-left')],
    'm-nav-right': () => [require('../../../mobile/src/m-nav-right')],
    'm-nav-title': () => [require('../../../mobile/src/m-nav-title')],
    'm-navbar': () => [require('../../../mobile/src/m-navbar')],
    'm-segmented': () => [require('../../../mobile/src/m-segmented')],
    'm-tab': () => [require('../../../mobile/src/m-tab')],
    'm-tabs': () => [require('../../../mobile/src/m-tabs')],
    'm-toolbar': () => [require('../../../mobile/src/m-toolbar')],
    'm-checkbox': () => [require('../../../mobile/src/m-checkbox')],
    'm-popup': () => [require('../../../mobile/src/m-popup')],
    'm-radio': () => [require('../../../mobile/src/m-radio')],
    'm-range': () => [require('../../../mobile/src/m-range')],
    'm-searchbar': () => [require('../../../mobile/src/m-searchbar')],
    'm-sheet': () => [require('../../../mobile/src/m-sheet')],
    'm-stepper': () => [require('../../../mobile/src/m-stepper')],
    'm-toggle': () => [require('../../../mobile/src/m-toggle')],
    'm-card': () => [require('../../../mobile/src/m-card')],
    'm-cardcontent': () => [require('../../../mobile/src/m-cardcontent')],
    'm-cardfooter': () => [require('../../../mobile/src/m-cardfooter')],
    'm-cardheader': () => [require('../../../mobile/src/m-cardheader')],
    'm-preloader': () => [require('../../../mobile/src/m-preloader')],
  }
}
